<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.25">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Results – IBD Cross-Cohort Microbiome Classification</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-7b89279ff1a6dce999919e0e67d4d9ec.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-27e1aa2dab5d6404f55602c9c9ab0aa1.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a href="./index.html" class="navbar-brand navbar-brand-logo">
    </a>
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">IBD Cross-Cohort Microbiome Classification</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html"> 
<span class="menu-text">Background</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./objectives.html"> 
<span class="menu-text">Objectives</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./data-methods.html"> 
<span class="menu-text">Data &amp; Cohort</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./methods.html"> 
<span class="menu-text">Methods</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link active" href="./results.html" aria-current="page"> 
<span class="menu-text">Results</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#cohort-structure-dominates-over-disease-status-and-we-account-for-it" id="toc-cohort-structure-dominates-over-disease-status-and-we-account-for-it" class="nav-link active" data-scroll-target="#cohort-structure-dominates-over-disease-status-and-we-account-for-it"><span class="header-section-number">1</span> 1. Cohort structure dominates over disease status — and we account for it</a></li>
  <li><a href="#alpha-diversity-significant-in-species-not-in-pathway" id="toc-alpha-diversity-significant-in-species-not-in-pathway" class="nav-link" data-scroll-target="#alpha-diversity-significant-in-species-not-in-pathway"><span class="header-section-number">2</span> 2. Alpha diversity: significant in species, not in pathway</a></li>
  <li><a href="#differential-abundance-three-independent-tests-species-vs.-pathway" id="toc-differential-abundance-three-independent-tests-species-vs.-pathway" class="nav-link" data-scroll-target="#differential-abundance-three-independent-tests-species-vs.-pathway"><span class="header-section-number">3</span> 3. Differential abundance: three independent tests, species vs.&nbsp;pathway</a>
  <ul class="collapse">
  <li><a href="#species-tier-1-and-tier-2-volcano-plots" id="toc-species-tier-1-and-tier-2-volcano-plots" class="nav-link" data-scroll-target="#species-tier-1-and-tier-2-volcano-plots"><span class="header-section-number">3.1</span> Species — Tier 1 and Tier 2 volcano plots</a></li>
  <li><a href="#pathway-blocked-wilcoxon-significant-features" id="toc-pathway-blocked-wilcoxon-significant-features" class="nav-link" data-scroll-target="#pathway-blocked-wilcoxon-significant-features"><span class="header-section-number">3.2</span> Pathway — blocked Wilcoxon significant features</a></li>
  <li><a href="#way-convergence-and-the-validated-species-signature" id="toc-way-convergence-and-the-validated-species-signature" class="nav-link" data-scroll-target="#way-convergence-and-the-validated-species-signature"><span class="header-section-number">3.3</span> 3-way convergence and the validated species signature</a></li>
  </ul></li>
  <li><a href="#feature-selection-rfe-panels" id="toc-feature-selection-rfe-panels" class="nav-link" data-scroll-target="#feature-selection-rfe-panels"><span class="header-section-number">4</span> 4. Feature selection: RFE panels</a></li>
  <li><a href="#machine-learning-model-performance" id="toc-machine-learning-model-performance" class="nav-link" data-scroll-target="#machine-learning-model-performance"><span class="header-section-number">5</span> 5. Machine learning: model performance</a>
  <ul class="collapse">
  <li><a href="#winning-models-per-feature-type" id="toc-winning-models-per-feature-type" class="nav-link" data-scroll-target="#winning-models-per-feature-type"><span class="header-section-number">5.1</span> Winning models per feature type</a></li>
  </ul></li>
  <li><a href="#leave-one-cohort-out-loco-validation" id="toc-leave-one-cohort-out-loco-validation" class="nav-link" data-scroll-target="#leave-one-cohort-out-loco-validation"><span class="header-section-number">6</span> 6. Leave-one-cohort-out (LOCO) validation</a></li>
  <li><a href="#model-interpretability-shap" id="toc-model-interpretability-shap" class="nav-link" data-scroll-target="#model-interpretability-shap"><span class="header-section-number">7</span> 7. Model interpretability: SHAP</a></li>
  <li><a href="#summary-convergent-evidence" id="toc-summary-convergent-evidence" class="nav-link" data-scroll-target="#summary-convergent-evidence"><span class="header-section-number">8</span> 8. Summary: convergent evidence</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Results</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="cohort-structure-dominates-over-disease-status-and-we-account-for-it" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="cohort-structure-dominates-over-disease-status-and-we-account-for-it"><span class="header-section-number">1</span> 1. Cohort structure dominates over disease status — and we account for it</h2>
<p>Before trusting any disease-association result, the pipeline first asked how much of the microbial compositional variance is explained by cohort of origin versus IBD status. The answer, consistently across both feature types and across every covariate-adjusted submodel: <strong>cohort explains roughly 6–13× more variance than IBD group.</strong></p>
<div id="fig-permanova" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-permanova-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/cohort_variance_permanova.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-permanova-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: PERMANOVA (Bray-Curtis, <code>by="margin"</code>) variance explained (R²) across four models, each fit on a different sample subset depending on covariate availability. <code>cohort</code> (green) dwarfs <code>group</code> (magenta) in every model; <code>age</code> and <code>gender</code> are independently significant but small; <code>BMI</code> is never significant.
</figcaption>
</figure>
</div>
<table class="caption-top table">
<colgroup>
<col style="width: 15%">
<col style="width: 21%">
<col style="width: 21%">
<col style="width: 21%">
<col style="width: 21%">
</colgroup>
<thead>
<tr class="header">
<th>Model</th>
<th style="text-align: right;">n</th>
<th style="text-align: right;">cohort R²</th>
<th style="text-align: right;">group R²</th>
<th style="text-align: right;">covariate R²</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>base (cohort + group), species</td>
<td style="text-align: right;">353</td>
<td style="text-align: right;">0.1233 (p=0.001)</td>
<td style="text-align: right;">0.0093 (p=0.001)</td>
<td style="text-align: right;">—</td>
</tr>
<tr class="even">
<td>base (cohort + group), pathway</td>
<td style="text-align: right;">352</td>
<td style="text-align: right;">0.1298 (p=0.001)</td>
<td style="text-align: right;">0.0105 (p=0.002)</td>
<td style="text-align: right;">—</td>
</tr>
<tr class="odd">
<td>+ age, species</td>
<td style="text-align: right;">173</td>
<td style="text-align: right;">0.1276 (p=0.001)</td>
<td style="text-align: right;">0.0108 (p=0.008)</td>
<td style="text-align: right;">age 0.0091 (p=0.031)</td>
</tr>
<tr class="even">
<td>+ age, pathway</td>
<td style="text-align: right;">173</td>
<td style="text-align: right;">0.1259 (p=0.001)</td>
<td style="text-align: right;">0.0131 (p=0.006)</td>
<td style="text-align: right;">age 0.0035 (p=0.611, n.s.)</td>
</tr>
<tr class="odd">
<td>+ gender, species</td>
<td style="text-align: right;">271</td>
<td style="text-align: right;">0.0665 (p=0.001)</td>
<td style="text-align: right;">0.0072 (p=0.008)</td>
<td style="text-align: right;">gender 0.0059 (p=0.037)</td>
</tr>
<tr class="even">
<td>+ gender, pathway</td>
<td style="text-align: right;">271</td>
<td style="text-align: right;">0.0722 (p=0.001)</td>
<td style="text-align: right;">0.0107 (p=0.007)</td>
<td style="text-align: right;">gender 0.0051 (p=0.152, n.s.)</td>
</tr>
<tr class="odd">
<td>+ BMI, species</td>
<td style="text-align: right;">223</td>
<td style="text-align: right;">0.0627 (p=0.001)</td>
<td style="text-align: right;">0.0078 (p=0.018)</td>
<td style="text-align: right;">BMI 0.0031 (p=0.777, n.s.)</td>
</tr>
<tr class="even">
<td>+ BMI, pathway</td>
<td style="text-align: right;">223</td>
<td style="text-align: right;">0.0661 (p=0.001)</td>
<td style="text-align: right;">0.0097 (p=0.026)</td>
<td style="text-align: right;">BMI 0.0055 (p=0.204, n.s.)</td>
</tr>
</tbody>
</table>
<p><em>Source: <code>results/tables/step6_permanova_summary.csv</code>, <code>step_pathway_permanova_summary.csv</code>.</em></p>
<p>The corresponding ordination confirms this visually: cohorts separate along PCoA1/PCoA2 far more clearly than IBD vs.&nbsp;control does within any single cohort (circle vs.&nbsp;triangle shapes are thoroughly intermixed within each cohort’s ellipse).</p>
<div id="fig-pcoa" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-pcoa-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/pcOA_betadiversity.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-pcoa-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: Bray-Curtis PCoA, species-level, colored by cohort and shaped by group. PCoA1 explains 15.6% of variance, PCoA2 9.3%. IjazUZ_2017 (green) is the most visually distinct cohort.
</figcaption>
</figure>
</div>
<p><strong>Practical consequence for everything downstream:</strong> the blocked Wilcoxon test explicitly blocks on cohort; both MaAsLin2 tiers include cohort as a random effect; and the ML validation strategy includes leave-one-cohort-out testing specifically because pooled cross-validation alone cannot rule out a model that has learned cohort identity rather than IBD biology.</p>
</section>
<section id="alpha-diversity-significant-in-species-not-in-pathway" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="alpha-diversity-significant-in-species-not-in-pathway"><span class="header-section-number">2</span> 2. Alpha diversity: significant in species, not in pathway</h2>
<p>Species-level alpha diversity is significantly reduced in IBD across all three metrics; pathway-level (functional) alpha diversity shows <strong>no significant difference</strong> — an important and genuine divergence between the taxonomic and functional layers, not an oversight.</p>
<div id="fig-alpha" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-alpha-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/AlphaDiver_species_pathway_boxplot.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-alpha-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3: Alpha diversity, species (top row) vs.&nbsp;pathway (bottom row). Species: richness p=0.0001, Shannon p&lt;0.0001, Simpson p=0.0001 (Wilcoxon, unadjusted). Pathway: richness p=0.882, Shannon p=0.578, Simpson p=0.260 — none significant.
</figcaption>
</figure>
</div>
<table class="caption-top table">
<colgroup>
<col style="width: 15%">
<col style="width: 21%">
<col style="width: 21%">
<col style="width: 21%">
<col style="width: 21%">
</colgroup>
<thead>
<tr class="header">
<th>Metric</th>
<th style="text-align: right;">Species Wilcoxon p (unadj.)</th>
<th style="text-align: right;">Species LME p (cohort-adj.)</th>
<th style="text-align: right;">Pathway Wilcoxon p (unadj.)</th>
<th style="text-align: right;">Pathway LME p (cohort-adj.)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Shannon</td>
<td style="text-align: right;">6.91×10⁻⁶</td>
<td style="text-align: right;">0.0021</td>
<td style="text-align: right;">0.578</td>
<td style="text-align: right;">0.898</td>
</tr>
<tr class="even">
<td>Simpson</td>
<td style="text-align: right;">8.59×10⁻⁵</td>
<td style="text-align: right;">0.0432</td>
<td style="text-align: right;">0.260</td>
<td style="text-align: right;">0.362</td>
</tr>
<tr class="odd">
<td>Richness</td>
<td style="text-align: right;">6.87×10⁻⁵</td>
<td style="text-align: right;">0.00022</td>
<td style="text-align: right;">0.882</td>
<td style="text-align: right;">0.802</td>
</tr>
</tbody>
</table>
<p><em>Source: <code>results/tables/step7_diversity_test_summary.csv</code>, <code>step_pathway_diversity_test_summary.csv</code>. The species result survives cohort-adjustment (LME), confirming it is not purely a cohort-composition artifact.</em></p>
</section>
<section id="differential-abundance-three-independent-tests-species-vs.-pathway" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="differential-abundance-three-independent-tests-species-vs.-pathway"><span class="header-section-number">3</span> 3. Differential abundance: three independent tests, species vs.&nbsp;pathway</h2>
<p>The species layer shows a strong, consistent differential-abundance signal across all three tests; the pathway layer shows a striking <strong>divergence</strong> between MaAsLin2 (almost no hits) and the blocked Wilcoxon test (many hits) — a finding worth featuring on its own.</p>
<div id="fig-da-summary" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-da-summary-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/signf_features_species_pathway_boxplot.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-da-summary-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4: Significant feature counts (q&lt;0.05) out of total tested, species (blue) vs.&nbsp;pathway (orange), across all three DA tests.
</figcaption>
</figure>
</div>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Test</th>
<th style="text-align: right;">Species hits / tested</th>
<th style="text-align: right;">Pathway hits / tested</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>MaAsLin2 Tier 1 (all samples, n=353/352)</td>
<td style="text-align: right;">65 / 151</td>
<td style="text-align: right;">1 / 118</td>
</tr>
<tr class="even">
<td>MaAsLin2 Tier 2 (age-adjusted, n=173)</td>
<td style="text-align: right;">24 / 151</td>
<td style="text-align: right;">1 / 118</td>
</tr>
<tr class="odd">
<td>Blocked Wilcoxon (cohort-blocked)</td>
<td style="text-align: right;">50 / 151</td>
<td style="text-align: right;">52 / 118</td>
</tr>
</tbody>
</table>
<p><em>Source: <code>step8_maaslin2_tier1_hit_summary.csv</code>, <code>step9_maaslin2_tier2_hit_summary.csv</code>, <code>step12_wilcoxon_hit_summary.csv</code> and pathway equivalents.</em> The pathway MaAsLin2 models are effectively null (1/118 in both tiers) while the pathway blocked Wilcoxon test finds nearly half the tested pathways significant (52/118) — a large discrepancy between a mixed-model and a rank-based, cohort-blocked non-parametric test on the same data, worth treating as a genuine methodological finding rather than picking one number to report.</p>
<section id="species-tier-1-and-tier-2-volcano-plots" class="level3" data-number="3.1">
<h3 data-number="3.1" class="anchored" data-anchor-id="species-tier-1-and-tier-2-volcano-plots"><span class="header-section-number">3.1</span> Species — Tier 1 and Tier 2 volcano plots</h3>
<div id="fig-volcano-t1" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-volcano-t1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/species_tier1_volcanoplot.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-volcano-t1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5: Species differential abundance, MaAsLin2 Tier 1 (all 353 samples). <em>Gemmiger formicilis</em> and <em>Ruminococcus bromii</em> are the two strongest depleted-in-IBD hits; <em>Erysipelatoclostridium ramosum</em> is the strongest enriched-in-IBD hit.
</figcaption>
</figure>
</div>
<div id="fig-volcano-t2" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-volcano-t2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/species_maaslintier2_volcanoplot.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-volcano-t2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6: Species differential abundance, MaAsLin2 Tier 2 (age-adjusted subset, n=173). The same top hits (<em>Gemmiger formicilis</em>, <em>Ruminococcus bromii</em>, <em>Adlercreutzia equolifaciens</em>, <em>Erysipelatoclostridium ramosum</em>) remain significant after adjusting for age and restricting to the smaller age-available subset — direct evidence the Tier 1 signal is not simply an age confound.
</figcaption>
</figure>
</div>
<div id="fig-volcano-wilcox" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-volcano-wilcox-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/blocked_wilcoxon_species.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-volcano-wilcox-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;7: Species differential abundance, cohort-blocked Wilcoxon test. Same top hits again — three independently-specified tests converge on the same leading species.
</figcaption>
</figure>
</div>
</section>
<section id="pathway-blocked-wilcoxon-significant-features" class="level3" data-number="3.2">
<h3 data-number="3.2" class="anchored" data-anchor-id="pathway-blocked-wilcoxon-significant-features"><span class="header-section-number">3.2</span> Pathway — blocked Wilcoxon significant features</h3>
<p>Every one of the 52 pathways significant by the blocked Wilcoxon test is <strong>lower in IBD</strong> — no pathway shows significant enrichment. This one-directional pattern (loss of function, not gain) is consistent across nearly all detected pathways, in contrast to species, where both depletion and enrichment hits exist.</p>
<div id="fig-pathway-wilcox" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-pathway-wilcox-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/pathway_blocekd_wilco_signffeature.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-pathway-wilcox-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;8: Pathways significant by blocked Wilcoxon (q&lt;0.05), ranked by log₂ fold-change (IBD/control, cohort-blocked). All are depleted in IBD.
</figcaption>
</figure>
</div>
</section>
<section id="way-convergence-and-the-validated-species-signature" class="level3" data-number="3.3">
<h3 data-number="3.3" class="anchored" data-anchor-id="way-convergence-and-the-validated-species-signature"><span class="header-section-number">3.3</span> 3-way convergence and the validated species signature</h3>
<p>Requiring agreement across MaAsLin2 Tier 1, MaAsLin2 Tier 2, and the blocked Wilcoxon test — the pipeline’s core evidentiary bar — leaves <strong>19 species</strong> as fully validated (“triple-candidates”), out of 65 Tier-1 hits.</p>
<div id="fig-venn" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-venn-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/overlapping_species.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-venn-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;9: 3-way overlap of species significance: MaAsLin2 Tier1, MaAsLin2 Tier2, and blocked Wilcoxon. 19 species pass all three tests; 29 pass Tier1+Wilcoxon but not the smaller-sample Tier2; only 2 pass Wilcoxon alone.
</figcaption>
</figure>
</div>
<p>Of the 19 triple-candidates, <strong>17 are depleted in IBD and 2 are enriched</strong> (<em>Erysipelatoclostridium ramosum</em>, <em>[Clostridium] symbiosum</em>) — both flagged as notable in Ning et al.&nbsp;2023 as well <span class="citation" data-cites="ning2023ccia">(<a href="#ref-ning2023ccia" role="doc-biblioref">Ning et al. 2023</a>)</span>. The signature is dominated by short-chain-fatty-acid-associated commensals (<em>Gemmiger formicilis</em>, <em>Ruminococcus bromii</em>, <em>Fusicatenibacter saccharivorans</em>, <em>[Eubacterium] rectale</em>).</p>
<div id="fig-triple" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-triple-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/specieS_dafeatures_RFE.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-triple-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;10: The 19-species triple-candidate signature, ranked by log₂ fold-change, with prevalence in IBD vs.&nbsp;control shown alongside. Most depleted species (green) show markedly lower prevalence in IBD than in control; the two enriched species (orange) show the reverse pattern.
</figcaption>
</figure>
</div>
<p>For reference, the full landscape of all 65 MaAsLin2-Tier1-significant species (i.e., before requiring 3-way agreement) is shown below — useful for seeing which additional species show a directionally consistent but less-replicated signal:</p>
<div id="fig-full-landscape" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-full-landscape-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/species_DA_Tier1_features.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-full-landscape-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;11: All 65 species significant in MaAsLin2 Tier 1, ranked by log₂ fold-change, with IBD/control prevalence bars.
</figcaption>
</figure>
</div>
</section>
</section>
<section id="feature-selection-rfe-panels" class="level2" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="feature-selection-rfe-panels"><span class="header-section-number">4</span> 4. Feature selection: RFE panels</h2>
<p>The 19-species and 18-pathway triple-candidate pools were reduced further via Recursive Feature Elimination, producing three panels each (optimum / parsimony / full pool):</p>
<div id="fig-rfe" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-rfe-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/rfe_feature_selection_curve.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-rfe-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;12: RFE cross-validated AUROC vs.&nbsp;panel size (random forest, 10-fold CV, ±SEM band), species (left) and pathway (right), with the three derived panel sizes marked.
</figcaption>
</figure>
</div>
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 26%">
<col style="width: 26%">
<col style="width: 26%">
</colgroup>
<thead>
<tr class="header">
<th>Feature type</th>
<th style="text-align: right;"><code>rfe_optimum</code></th>
<th style="text-align: right;"><code>rfe_parsimony</code> (1% tol.)</th>
<th style="text-align: right;"><code>rfe_full_pool</code></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Species</td>
<td style="text-align: right;">17</td>
<td style="text-align: right;">12</td>
<td style="text-align: right;">19</td>
</tr>
<tr class="even">
<td>Pathway</td>
<td style="text-align: right;">12</td>
<td style="text-align: right;">9</td>
<td style="text-align: right;">18</td>
</tr>
</tbody>
</table>
<p>Note the species curve is nearly flat from ~12 features onward (0.821 at 12 → 0.827 at 17 → 0.827 at 19) — the parsimonious 12-feature panel captures nearly all of the achievable cross-validated signal, which foreshadows the ML sweep result below (the 17-feature <code>rfe_optimum</code> panel wins by only 0.003 AUROC over <code>rfe_parsimony</code>).</p>
</section>
<section id="machine-learning-model-performance" class="level2" data-number="5">
<h2 data-number="5" class="anchored" data-anchor-id="machine-learning-model-performance"><span class="header-section-number">5</span> 5. Machine learning: model performance</h2>
<section id="winning-models-per-feature-type" class="level3" data-number="5.1">
<h3 data-number="5.1" class="anchored" data-anchor-id="winning-models-per-feature-type"><span class="header-section-number">5.1</span> Winning models per feature type</h3>
<p>Across the full sweep (4 model families × 3 panels for species and pathway; 4 model families × 1 panel for combined — 28 nested-CV runs total, 10×5 repeated stratified CV, Optuna-tuned), <strong>ElasticNet won in every feature type</strong>:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Feature type</th>
<th>Winning config</th>
<th style="text-align: right;">AUROC</th>
<th style="text-align: right;">AUPRC</th>
<th style="text-align: right;">n features</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Species</td>
<td>ElasticNet, <code>rfe_optimum</code></td>
<td style="text-align: right;">0.8325</td>
<td style="text-align: right;">0.888</td>
<td style="text-align: right;">17</td>
</tr>
<tr class="even">
<td>Pathway</td>
<td>ElasticNet, <code>rfe_full_pool</code></td>
<td style="text-align: right;">0.6916</td>
<td style="text-align: right;">0.787</td>
<td style="text-align: right;">18</td>
</tr>
<tr class="odd">
<td>Combined</td>
<td>ElasticNet, <code>rfe_full_pool</code></td>
<td style="text-align: right;">0.8313</td>
<td style="text-align: right;">0.888</td>
<td style="text-align: right;">37</td>
</tr>
</tbody>
</table>
<p>A regularized linear model consistently beating three more flexible nonlinear ensembles, at n≈350 samples and 12–37 features, is itself a finding worth stating plainly: there isn’t enough data/signal in this regime for the trees’ extra flexibility to pay off, and L1/L2 regularization is doing real work.</p>
<p><strong>Combining species and pathway barely improves over species alone</strong> (0.8313 vs.&nbsp;0.8325 AUROC) despite more than doubling the feature count (37 vs.&nbsp;17) — the added pathway features contribute little beyond what species already captures (confirmed independently by the SHAP analysis below).</p>
<div id="fig-roc" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-roc-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/auroc_curve.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-roc-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;13: ROC curves (mean ± 1 SD across 5 CV repeats) for the winning ElasticNet configuration per feature type. Real per-fold out-of-fold predictions (n=353 species / n=352 pathway &amp; combined), not synthetic.
</figcaption>
</figure>
</div>
<div id="fig-pr" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-pr-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/precision_recall_curve.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-pr-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;14: Precision-recall curves for the same three winning configurations, with baseline prevalence shown as a reference line.
</figcaption>
</figure>
</div>
<div id="fig-cm" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-cm-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/confusion_matrix.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-cm-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;15: Confusion matrices at the standard 0.5 probability threshold, one representative out-of-fold CV repeat per feature type.
</figcaption>
</figure>
</div>
<p>The species classifier correctly identifies 192/217 IBD subjects (88% sensitivity) and 82/136 controls (60% specificity) at the default threshold; the pathway classifier’s much lower ceiling is visible directly in its confusion matrix (71% of true controls misclassified as IBD).</p>
</section>
</section>
<section id="leave-one-cohort-out-loco-validation" class="level2" data-number="6">
<h2 data-number="6" class="anchored" data-anchor-id="leave-one-cohort-out-loco-validation"><span class="header-section-number">6</span> 6. Leave-one-cohort-out (LOCO) validation</h2>
<p>Pooled cross-validation cannot rule out a model that has learned cohort identity rather than disease biology — precisely the failure mode the PERMANOVA result (§1) warns is plausible here. LOCO trains on three cohorts and tests entirely on the fourth, held-out cohort (ElasticNet, <code>rfe_full_pool</code> panel, per feature type — note this is not necessarily each feature type’s pooled-CV <em>winning</em> panel, since species’ pooled winner was <code>rfe_optimum</code>; LOCO fixes <code>rfe_full_pool</code> across all three feature types for a controlled comparison).</p>
<div id="fig-loco" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-loco-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/loco_validation.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-loco-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;16: LOCO AUROC by held-out cohort and feature type. Dashed line = chance (0.5). Single train/test split per cohort — no repeat variance is available (unlike the paper convention of n=5 repeated LOCO runs), so no error bars are shown; this is a real limitation of the current LOCO setup, not an omission.
</figcaption>
</figure>
</div>
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 26%">
<col style="width: 26%">
<col style="width: 26%">
</colgroup>
<thead>
<tr class="header">
<th>Held-out cohort</th>
<th style="text-align: right;">Species AUROC (n test)</th>
<th style="text-align: right;">Pathway AUROC (n test)</th>
<th style="text-align: right;">Combined AUROC (n test)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>HMP_2019_ibdmdb</td>
<td style="text-align: right;">0.758 (130)</td>
<td style="text-align: right;">0.618 (130)</td>
<td style="text-align: right;">0.786 (130)</td>
</tr>
<tr class="even">
<td>HallAB_2017</td>
<td style="text-align: right;">0.800 (32)</td>
<td style="text-align: right;"><strong>0.329 (31)</strong></td>
<td style="text-align: right;">0.803 (31)</td>
</tr>
<tr class="odd">
<td>IjazUZ_2017</td>
<td style="text-align: right;">0.958 (50)</td>
<td style="text-align: right;">0.800 (50)</td>
<td style="text-align: right;">0.974 (50)</td>
</tr>
<tr class="even">
<td>NielsenHB_2014</td>
<td style="text-align: right;">0.707 (141)</td>
<td style="text-align: right;">0.578 (141)</td>
<td style="text-align: right;">0.691 (141)</td>
</tr>
</tbody>
</table>
<p><em>Source: <code>results/tables/loco_summary_all.csv</code>.</em> Species and combined models generalize reasonably across all four held-out cohorts (0.71–0.97 AUROC). The pathway model <strong>collapses to worse than chance on HallAB_2017</strong> (AUROC 0.329, n=31) — the smallest held-out test set among the four cohorts, and consistent with the pathway layer’s already-weaker and more test-dependent signal (§3). This is flagged as an honest limitation, not smoothed over.</p>
</section>
<section id="model-interpretability-shap" class="level2" data-number="7">
<h2 data-number="7" class="anchored" data-anchor-id="model-interpretability-shap"><span class="header-section-number">7</span> 7. Model interpretability: SHAP</h2>
<p>SHAP values are available only for the <strong>combined</strong> model (species+pathway, 37 features, n=352) — no separate SHAP run exists per feature type.</p>
<div id="fig-shap" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-shap-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/feature_importance_shap.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-shap-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;17: Top-20 SHAP feature importances, combined ElasticNet model. Red = high (CLR-transformed) feature value, blue = low. Positive SHAP value pushes the prediction toward IBD.
</figcaption>
</figure>
</div>
<p><strong>Species features dominate the combined model’s predictions: 88.3% of total |SHAP| mass comes from species features, versus 11.7% from pathway features</strong> (<code>combined_shap_contribution_by_type.csv</code>) — direct, model-internal confirmation of the near-zero benefit from adding pathway features observed in the AUROC comparison above (§5). The six highest-ranked SHAP features (<em>Adlercreutzia equolifaciens</em>, <em>Gemmiger formicilis</em>, <em>Ruminococcus bromii</em>, <em>[Ruminococcus] torques</em>, <em>Alistipes putredinis</em>, <em>[Clostridium] leptum</em>) are <strong>all</strong> members of the 19-species triple-candidate signature identified independently by the statistical DA pipeline (§3) — convergence between an ML model’s learned feature importances and an independently-validated statistical signature, obtained via entirely different methodology, is the strongest piece of corroborating evidence in this project.</p>
</section>
<section id="summary-convergent-evidence" class="level2" data-number="8">
<h2 data-number="8" class="anchored" data-anchor-id="summary-convergent-evidence"><span class="header-section-number">8</span> 8. Summary: convergent evidence</h2>
<p>Putting the independent lines of evidence side by side:</p>
<ul>
<li><strong>Statistical DA</strong> (3-way MaAsLin2×2 + blocked Wilcoxon convergence): 19 validated species</li>
<li><strong>RFE</strong> (<code>rfe_optimum</code>, cross-validated AUROC-maximizing subset of those 19): 17 species</li>
<li><strong>SHAP</strong> (combined ElasticNet’s top-ranked features): top 6 are all triple-candidates</li>
<li><strong>ML performance</strong>: the RFE-optimum 17-species ElasticNet panel achieves 0.8325 AUROC pooled, and 0.71–0.96 AUROC across all four LOCO held-out cohorts</li>
</ul>
<p>Three independently-specified statistical tests, an independent feature-selection procedure, and a fully independent nested-CV/Optuna-tuned classifier trained without any knowledge of the DA results all converge on substantially the same small set of species — <em>Gemmiger formicilis</em>, <em>Ruminococcus bromii</em>, <em>Adlercreutzia equolifaciens</em>, <em>Alistipes putredinis</em> foremost among them. That convergence, more than any single AUROC number, is this project’s central empirical result.</p>



</section>

<div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography" id="quarto-bibliography"><h2 class="anchored quarto-appendix-heading">References</h2><div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list">
<div id="ref-ning2023ccia" class="csl-entry" role="listitem">
Ning, Lijun, Yi-Lu Zhou, Han Sun, Youwei Zhang, Chaoqin Shen, Zhenhua Wang, Baoqin Xuan, et al. 2023. <span>“Microbiome and Metabolome Features in Inflammatory Bowel Disease via Multi-Omics Integration Analyses Across Cohorts.”</span> <em>Nature Communications</em> 14: 7135. <a href="https://doi.org/10.1038/s41467-023-42788-0">https://doi.org/10.1038/s41467-023-42788-0</a>.
</div>
</div></section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/Sanyukta2002\.github\.io\/ML-ibd\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>IBD cross-cohort microbiome pipeline</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
<p>Built with Quarto</p>
</div>
  </div>
</footer>




</body></html>